---
sudo: required
language: python
env:
  - MOLECULE_DISTRO=fedora33   ANSIBLE_ROLES_PATH=.. PY_COLORS='1' ANSIBLE_FORCE_COLOR:=1 DOCKER_TLS_CERTDIR="/certs"
  - MOLECULE_DISTRO=debian9    ANSIBLE_ROLES_PATH=.. PY_COLORS='1' ANSIBLE_FORCE_COLOR:=1 DOCKER_TLS_CERTDIR="/certs"
  - MOLECULE_DISTRO=debian10   ANSIBLE_ROLES_PATH=.. PY_COLORS='1' ANSIBLE_FORCE_COLOR:=1 DOCKER_TLS_CERTDIR="/certs"
  - MOLECULE_DISTRO=ubuntu1604 ANSIBLE_ROLES_PATH=.. PY_COLORS='1' ANSIBLE_FORCE_COLOR:=1 DOCKER_TLS_CERTDIR="/certs"
  - MOLECULE_DISTRO=ubuntu1804 ANSIBLE_ROLES_PATH=.. PY_COLORS='1' ANSIBLE_FORCE_COLOR:=1 DOCKER_TLS_CERTDIR="/certs"
  - MOLECULE_DISTRO=ubuntu2004 ANSIBLE_ROLES_PATH=.. PY_COLORS='1' ANSIBLE_FORCE_COLOR:=1 DOCKER_TLS_CERTDIR="/certs"
  - MOLECULE_DISTRO=centos7    ANSIBLE_ROLES_PATH=.. PY_COLORS='1' ANSIBLE_FORCE_COLOR:=1 DOCKER_TLS_CERTDIR="/certs"
#  - MOLECULE_DISTRO=centos8    ANSIBLE_ROLES_PATH=.. PY_COLORS='1' ANSIBLE_FORCE_COLOR:=1 DOCKER_TLS_CERTDIR="/certs"
before_install:
#/etc/default/docker
  - echo 'DOCKER_OPTS="$DOCKER_OPTS --debug --registry-mirror=https://mirror.gcr.io"' | sudo tee -a /etc/default/docker
  - sudo service docker restart
  - docker system info
services:
  - docker
install:
  - python3 -m pip install molecule molecule-docker ansible
script:
#  - molecule converge
  - molecule test

#notifications:
#  webhooks: https://galaxy.ansible.com/api/v1/notifications/
